services:

  api:
    build: .
    container_name: api-pizzaria

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

    volumes:
      - .:/app

  db:
    image: postgres:17

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pizzaria

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: